name: photos_sync
description: A Flutter app to sync photos to/from a remote server.
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 0.1.3
  provider: 4.0.2
  http: ^0.12.0+4
  # google
  firebase_auth: 0.15.3
  cloud_firestore: 0.13.0+1
  firebase_storage: 3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flappy_translator: 1.2.0

flutter:
  uses-material-design: true

# settings for flappy_translator package
flappy_translator:
  input_file_path: "assets_dev/loca/loca.csv"
  output_dir: "lib"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ";"
  start_index: 2
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false