name: photos_sync
description: A Flutter app to sync photos to/from a remote server.
push_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  provider:
  shared_preferences:
  path_provider:
  # google
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  # third party
  file_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flappy_translator: 2.0.0-nullsafety.2

flutter:
  uses-material-design: true

# settings for flappy_translator package
flappy_translator:
  input_file_path: "assets_dev/loca/loca.csv"
  output_dir: "lib"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ";"
  start_index: 2
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false

